"""files save separately

Revision ID: db01f2a1626c
Revises: 6cf75f26689c
Create Date: 2025-12-27 18:27:59.569272

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db01f2a1626c'
down_revision: Union[str, Sequence[str], None] = '6cf75f26689c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('file_path', sa.String(), nullable=True))
    op.drop_column('documents', 'binary_content')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('binary_content', sa.BLOB(), nullable=True))
    op.drop_column('documents', 'file_path')
    # ### end Alembic commands ###
